# Step 1: Base Image
FROM node:18-alpine 
RUN npm install -g nodemon
# Step 2: Working directory
# WORKDIR /app

# Step 3: Copy package files
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy all project files
# COPY . .

# Step 6: Expose port
EXPOSE 5000

# Step 7: Run server
CMD ["npm", "start"]

# create image  docker buildx build -t my-node-app . in docker
# create volume  command docker run --name basic-container ` -p 5000:5000 ` --rm `-v D:\Shadi\backend:/app `my-node-app:v2
# docker compose up